@startuml
!pragma layout smetana

main --> loginPage
loginPage --> menu
menu *-- homePage
menu *-- workoutPage
menu *-- accountPage
menu *-- orderTren
account --> accountPage
workoutPage <-- exercises
"util" --* menu
"util" --* loginPage
sets --* exercises

class main {
+ static void main(String[] args)
- loginPage login;
+ login.runLogin()

}

class loginPage {
- String username
- String password
- account acc
- menu menu
- accountMapper am

' Constructor
+ loginPage()

' Metoder
+ void runLogin()
+ void createAccount()[menu.runMenu()]
+ void login()[menu.runMenu()]

}
class menu {
- homePage hp;
- workoutPage wp;
- orderTren ot;
- accountPage ap;
+ menu()
+ void runAlways()
+  homePage()
+  workoutPage()
+  orderTren()
+  accountPage()


}
class homePage {
+ homePage()
+ void displayTrainingHistory()
}
class workoutPage {
- currentTraining ct
- exercisesMapper em
+ workoutPage()
+ startTraining()

}

workoutPage *-- currentTraining

class currentTraining{
+ void startTraining()
+ void newTrainingProgram()
+ void existingTrainingProgram()
+ void endTraining()
+ void editTraining()
+ Getter & Setter()
}

class accountPage {
+ accountPage()
+ void displayAccountInfo()
+ void changePassword()
+ void setMeasurements()([setInputHeight, setInputWeight])
+ void logOut()

}
class orderTren {
+ orderTren()
+ void orderTren()

}
class exercises {
+ exercises()
- String exerciseName
- String note
- List<sets> exercise


+ void addSetsToExercise()
- sets set1 = new sets()
- sets set2 = new sets()
- sets set3 = new sets()
- exercise.add(set1)
- exercise.add(set2)
- exercise.add(set3)




+ exercises(String exerciseName, list<sets> exercise, String note, )


}

class account {
- String username
- String password
- float inputWeight
- float inputHeight

+ account(String username, String password, float inputWeight, float inputHeight
+ Getter & Setter()

}
class sets {
- int reps
- float kg

+ sets(int reps, float kg)

+ Getter & Setter()
}

package "util" {
class accountMapper {
+ accountMapper()
- List<account> account

+List<account> loadAccountData()
+List<account> saveAccountData()
}

class exercisesMapper {
+ exerciseMapper()
+ List<exercises> loadExercisesData()
+ List<exercises> saveExercisesData()
}
}
@enduml